
import FenetreVictoire.FenetreVictoire;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import lightoff_pradeau_version_console.GrilleDeCellules;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Utilisateur
 */
public class FenetrePrincipale extends javax.swing.JFrame {
GrilleDeCellules grille;
int nbCoups;
 JLabel finDePartieLabel;
 


    /**
     * Creates new form FenetrePrincipale
     */
    public  FenetrePrincipale() {
        
        initComponents();
        int nbLignes = 10;
int nbColonnes = 10;
this.grille = new GrilleDeCellules(nbLignes, nbColonnes);
grille.melangerMatriceAleatoirement(100);
PanneauGrille.setLayout(new GridLayout(nbLignes, nbColonnes));
for (int i=0; i < nbLignes; i++) {
 for (int j=0; j < nbColonnes; j++ ) {
 CelluleGraphique bouton_cellule = new CelluleGraphique( grille.matriceCellules[i][j], 40,40);
 PanneauGrille.add(bouton_cellule); // ajout au Jpanel PanneauGrille
 
 }
}
PanneauBoutonVerticaux.setLayout(new GridLayout(nbLignes, 1));
 getContentPane().add(PanneauBoutonVerticaux, new
org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1 * 40, nbLignes * 40));
 for (int i = 0; i < nbLignes; i++) {
            JButton bouton_ligne = new JButton();
            final int j = i;
            bouton_ligne.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    grille.activerLigneDeCellules(j);
                    repaint();
                }
            });
            PanneauBoutonVerticaux.add(bouton_ligne);
        }
 this.pack();
 this.revalidate();
 
 jPanel1.setLayout(new GridLayout(nbColonnes, 1));
 getContentPane().add(jPanel1, new
org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1 * 40, nbColonnes * 40));
 for (int i = 0; i < nbColonnes; i++) {
            JButton bouton_colonne = new JButton();
            final int j = i;
            bouton_colonne.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    grille.activerColonneDeCellules(j);
                    repaint();
                }
            });
            jPanel1.add(bouton_colonne);
        }
 this.pack();
 this.revalidate();
 

    }

public void initialiserPartie() {
        grille.eteindreToutesLesCellules();
        grille.melangerMatriceAleatoirement(10);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLigne1 = new java.awt.Button();
        PanneauGrille = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        PanneauBoutonVerticaux = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnLigne0 = new java.awt.Button();
        btnligne1 = new java.awt.Button();
        btnLigne2 = new java.awt.Button();
        btnLigne3 = new java.awt.Button();
        btnLigne4 = new java.awt.Button();
        btnLigne5 = new java.awt.Button();
        btnLigne6 = new java.awt.Button();
        btnLigne7 = new java.awt.Button();
        btnLigne8 = new java.awt.Button();
        btnLigne9 = new java.awt.Button();
        jButton11 = new javax.swing.JButton();

        btnLigne1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(102, 102, 255));
        PanneauGrille.setToolTipText("");

        javax.swing.GroupLayout PanneauGrilleLayout = new javax.swing.GroupLayout(PanneauGrille);
        PanneauGrille.setLayout(PanneauGrilleLayout);
        PanneauGrilleLayout.setHorizontalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanneauGrilleLayout.setVerticalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 400, 400));

        jButton1.setText("BtnCln0");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jButton2.setText("BtnCln1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        jButton3.setText("BtnCln2");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jButton4.setText("BtnCln3");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, -1, -1));

        jButton5.setText("BtnCln4");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jButton6.setText("BtnCln5");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, -1, -1));

        jButton7.setText("BtnCln6");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        jButton8.setText("BtnCln7");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, -1, -1));

        jButton9.setText("BtnCln8");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        jButton10.setText("BtnCln9");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, -1, -1));

        PanneauBoutonVerticaux.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout PanneauBoutonVerticauxLayout = new javax.swing.GroupLayout(PanneauBoutonVerticaux);
        PanneauBoutonVerticaux.setLayout(PanneauBoutonVerticauxLayout);
        PanneauBoutonVerticauxLayout.setHorizontalGroup(
            PanneauBoutonVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        PanneauBoutonVerticauxLayout.setVerticalGroup(
            PanneauBoutonVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauBoutonVerticaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 80, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, -1, -1));

        btnLigne0.setLabel("button1");
        btnLigne0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne0ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne0, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        btnligne1.setLabel("button2");
        btnligne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnligne1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnligne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        btnLigne2.setLabel("button3");
        btnLigne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        btnLigne3.setLabel("button4");
        btnLigne3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        btnLigne4.setLabel("button5");
        btnLigne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        btnLigne5.setLabel("button6");
        btnLigne5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        btnLigne6.setLabel("button7");
        btnLigne6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        btnLigne7.setLabel("button8");
        btnLigne7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        btnLigne8.setLabel("button9");
        btnLigne8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        btnLigne9.setLabel("button1");
        btnLigne9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigne9ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigne9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        jButton11.setText("BtnDiago");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLigne0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne0ActionPerformed
         this.grille.activerLigneDeCellules(0);
         nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();

    }//GEN-LAST:event_btnLigne0ActionPerformed

    private void btnligne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnligne1ActionPerformed
        this.grille.activerLigneDeCellules(1);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();
    }//GEN-LAST:event_btnligne1ActionPerformed

    private void btnLigne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne2ActionPerformed
        this.grille.activerLigneDeCellules(2);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();
    }//GEN-LAST:event_btnLigne2ActionPerformed

    private void btnLigne3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne3ActionPerformed
        this.grille.activerLigneDeCellules(3);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();
    }//GEN-LAST:event_btnLigne3ActionPerformed

    private void btnLigne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne4ActionPerformed
       this.grille.activerLigneDeCellules(4);
       nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();
    }//GEN-LAST:event_btnLigne4ActionPerformed

    private void btnLigne5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne5ActionPerformed
        this.grille.activerLigneDeCellules(5);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();
    }//GEN-LAST:event_btnLigne5ActionPerformed

    private void btnLigne6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne6ActionPerformed
        this.grille.activerLigneDeCellules(6);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();
    }//GEN-LAST:event_btnLigne6ActionPerformed

    private void btnLigne7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne7ActionPerformed
        this.grille.activerLigneDeCellules(7);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();
    }//GEN-LAST:event_btnLigne7ActionPerformed

    private void btnLigne8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne8ActionPerformed
        this.grille.activerLigneDeCellules(8);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();
    }//GEN-LAST:event_btnLigne8ActionPerformed

    private void btnLigne9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigne9ActionPerformed
        this.grille.activerLigneDeCellules(9);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();
    }//GEN-LAST:event_btnLigne9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.grille.activerColonneDeCellules(9);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.grille.activerColonneDeCellules(0);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.grille.activerColonneDeCellules(1);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.grille.activerColonneDeCellules(2);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.grille.activerColonneDeCellules(3);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.grille.activerColonneDeCellules(4);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.grille.activerColonneDeCellules(5);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.grille.activerColonneDeCellules(6);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.grille.activerColonneDeCellules(7);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.grille.activerColonneDeCellules(8);
        nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
         this.grille.activerDiagonaleDescendante();
         nbCoups++;
         if (grille.cellulesToutesEteintes()) {FenetreVictoire f = new FenetreVictoire() ;
f.setVisible(true) ;}
 repaint();
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Couverture f = new Couverture() ;
f.setVisible(true) ; 
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauBoutonVerticaux;
    private javax.swing.JPanel PanneauGrille;
    private java.awt.Button btnLigne0;
    private java.awt.Button btnLigne1;
    private java.awt.Button btnLigne2;
    private java.awt.Button btnLigne3;
    private java.awt.Button btnLigne4;
    private java.awt.Button btnLigne5;
    private java.awt.Button btnLigne6;
    private java.awt.Button btnLigne7;
    private java.awt.Button btnLigne8;
    private java.awt.Button btnLigne9;
    private java.awt.Button btnligne1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private int getNbCoups() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
